apiVersion: batch/v1
kind: Job
metadata:
  name: pre-install-hook
  namespace: {{ .Values.namespace }}
spec:
  template:
    spec:
      containers:
        - name: pre-install-hook
          image: alpine:latest
          command: ["echo", "Executing pre-installation hook"]
      restartPolicy: Never
  backoffLimit: 1